language: go
go:
 - 1.2
 - 1.3
 - release

before_install:
  - go get github.com/soniah/gosnmp
  - go get github.com/stretchr/testify/assert
  - go get github.com/axw/gocov/gocov
  - go get github.com/mattn/goveralls
  - go get code.google.com/p/go.tools/cmd/cover

script:
  - go test -v ./...
