language: go
go:
 - 1.4
 - 1.5
 - 1.6
 - tip

before_install:
  - make deps

install:
  - make build

script:
  - make test
  - $HOME/gopath/bin/goveralls -repotoken 0A8ycTAs0NU3E8rureuBUPzgHbpZ1qZA5
