language: go
go:
 - 1.11.x
 - 1.17.x

sudo: false

# safelist branch to build
branches:
  only:
    - master

script:
  - go get github.com/streadway/amqp
  - make jenkins

notifications:
  email:
  - bifer@alea-soluciones.com
